name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v16
        with:
          name: rstats-on-nix
          # If you chose signing key for write access
          # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH }}'

      - name: Build environment
        run: nix-build

      - name: Build environment for tests
        run: nix-build tests/default.nix

      - name: Run tests inside nix-shell (uses default.nix)
        run: |
          set -euo pipefail
          # Use the default.nix in the repo to provide the dev environment,
          # then run pytest inside that environment.
          nix-shell --run "pytest -q"
        shell: bash
